# Generated by Django 4.1.7 on 2025-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/viseo/%Y/%m/%d/'),
        ),
    ]
